server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      path: /db

jwt:
  secret: kotlin-board-api-user-sceret-key